name: SPM Continuous Integration

on:
    push:
        branches:
            - master
            - staging

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Setup NodeJS
              uses: actions/setup-node@v2
              with:
                  node-version: 18

            - name: Install Dependencies
              run: npm install

            - name: Build ReactJS app
              run: npm run build
